const data = [
	{
		id: 1,
		name: 'Kompleks Belia Dan Sukan Kuala Lumpur',
		employee_no: 87,
		status: 'Active',
		line_add_1: '4029, Jalan Kampung Pandan',
		line_add_2: 'Maluri',
		postal_code: 55100,
		city: 'Kuala Lumpur',
		state: 'Kuala Lumpur',
	},
	{
		id: 2,
		name: 'Y-Centre UTC Kuala Lumpur',
		employee_no: 45,
		status: 'Active',
		line_add_1: 'Lot T-4, Tingkat 4',
		line_add_2: 'UTC KL @ Pudu Sentral Jln Pudu',
		postal_code: 57000,
		city: 'Kuala Lumpur',
		state: 'Kuala Lumpur',
	},
	{
		id: 3,
		name: 'Velodrom Nasional Malaysia',
		employee_no: 102,
		status: 'Active',
		line_add_1: 'Lot 16074, Persiaran Perbandaran',
		line_add_2: 'Bandar Baru Nilai',
		postal_code: 71800,
		city: 'Nilai',
		state: 'Negeri Sembilan',
	},
	{
		id: 4,
		name: 'Kompleks MSN Bukit Jalil',
		employee_no: 321,
		status: 'Active',
		line_add_1: 'Jalan Barat',
		line_add_2: 'Bukit Jalil',
		postal_code: 57000,
		city: 'Kuala Lumpur',
		state: 'Kuala Lumpur',
	},
	{
		id: 5,
		name: 'Kompleks Belia Dan Sukan Sabah',
		employee_no: 124,
		status: 'Inactive',
		line_add_1: 'Jalan Taman Pasir Putih',
		line_add_2: 'Bandar Putatan',
		postal_code: 89500,
		city: 'Kota Kinabalu',
		state: 'Sabah',
	},
];

export default data;
